### ISSUE TITLE
1.14 exiting portal on server disconnects you and then kills you when you rejoin a server

### ISSUE THREAD

**Issue by SDUBZ** [Draylar/miners_horizon#1]
net.minecraft.class_148: Colliding entity with blockat net.minecraft.class_3222.method_14226(class_3222.java:450) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:194) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:842) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]Caused by: java.lang.NoSuchMethodError: net.minecraft.class_3218.method_8395()Lnet/minecraft/class_2338;at com.github.draylar.miners_horizon.common.world.TeleportPlacementHandler.leaveDimension(TeleportPlacementHandler.java:88) ~[miners-horizon-1.1.0.jar:?]at net.minecraft.class_1946.handler$method_8653$zbh000(class_1946.java:533) ~[intermediary-server.jar:?]at net.minecraft.class_1946.method_8653(class_1946.java) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_5731(class_3222.java:699) ~[intermediary-server.jar:?]at com.github.draylar.miners_horizon.common.blocks.portal.MinerPortalBlock.method_9548(MinerPortalBlock.java:44) ~[miners-horizon-1.1.0.jar:?]at net.minecraft.class_2680.method_11613(class_2680.java:270) ~[intermediary-server.jar:?]at net.minecraft.class_1297.method_5852(class_1297.java:859) ~[intermediary-server.jar:?]at net.minecraft.class_1297.method_5784(class_1297.java:612) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1952) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1533) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2287) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:545) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2102) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:262) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:386) ~[intermediary-server.jar:?]... 8 more[23:59:45] [Server thread/INFO]: swh65458 lost connection: Internal server error[23:59:45] [Server thread/INFO]: swh65458 left the game

**Comment by Draylar** [comment]
Hi SDUBZ, I _think_ I've fixed this in the latest version (1.2.0). I'm going to keep this issue open until I've confirmed it's fixed. Thanks for the report!

**Comment by SDUBZ** [comment]
I updated juts before the one you just released can confirm no one had died from portal since then
