### ISSUE TITLE
1.14.1 Server with 1.4.0 miners_horizon crashes upon joining the dimension

### ISSUE THREAD

**Issue by daszh** [Draylar/miners_horizon#10]
Love the mod, and worked fine until the last update, but the last update might've broken something.

I'm running this on a dedicated Server and it keeps crashing whenever I enter the miners-horizon Dimension, Overworld or Nether are fine and everything else is fine.

I migrated a world from minecraft 1.14 and the miners-horizon_1.14-1.3.1 Version of the mod, but also if I fully delete the current save and let the server re-generate an entirely new save (Overworld, Nether and mining-dimension) the crash still happens.

When I import the same  world into Singleplayer, it seems to work.

Link to the Server Log: https://pastebin.com/j9gHJN1a

Would love to continue playing with this mod, I really like it!

**Comment by Draylar** [comment]
Fixed in 0ad2805. You _should_ be able to keep your existing Miner's Horizon dimension. Thanks!
