### ISSUE TITLE
cant enter dimension, only hear sounds.

### ISSUE THREAD

**Issue by Vortetty** [Draylar/miners_horizon#11]
i open the portal, and attempt to go to the dimension by standing in it, it just acts as if it was an open door. i dont get teleported to the dimension, i just stand in the portal.

**Comment by ButtonBright0907** [comment]
Did you press shift (crouch) while in the door?

**Comment by Vortetty** [comment]
No, I will try this. Do you also know how to fix the white redstone bug?

**Comment by Draylar** [comment]
Press shift to teleport :)
