### ISSUE TITLE
Other mods ores don't spawn despite being added in the config

### ISSUE THREAD

**Issue by angelnc1989** [Draylar/miners_horizon#3]
I added the ores from Refined Machinery to the json file, but they don't spawn at all. Vanilla ores spawn normally.

[This](https://pastebin.com/esBsri9K) is my config file.

**Comment by Draylar** [comment]
This has been fixed in 1.2.0 (latest release). Thank you for the report!

**Comment by angelnc1989** [comment]
Non-vanilla ores still don't spawn for me.
