### ISSUE TITLE
Miners Horizon 1.2.0: Diamond pickaxe seriously slowed down

### ISSUE THREAD

**Issue by Knito58** [Draylar/miners_horizon#6]
My diamond pickaxe mined like it was a cobble pickaxe. (Overworld). After going back to mod version 1.1.0 the diamond pickaxe seems to work on normal speed again.

**Comment by Draylar** [comment]
Fixed in 1.3.0/1.3.1. Accidentally did a mixin goof. Thanks for the report!

**Comment by Knito58** [comment]
yes its fixed :)
