### ISSUE TITLE
How to config ore gen ? (not an issue)

### ISSUE THREAD

**Issue by LeQwouincy** [Draylar/miners_horizon#7]
Hey !
As said in the title how can i change the mod's config ?
(will also help for every other mods)

**Comment by Draylar** [comment]
Hi LeQwouincy, you can find the mods config file in your config folder; it should be named "minershorizon.json." This has basic configuration options as well as a section for adding special ore types to generation. I will keep this issue open until I write some sort of small wiki page on it. Thanks!

**Comment by LeQwouincy** [comment]
Found it, thanks !
