### ISSUE TITLE
Where is my gold ?!

### ISSUE THREAD

**Issue by LeQwouincy** [Draylar/miners_horizon#8]
Hey !
Look like there is no gold ore gen.
Tried to redownload several time, plus modify config, but gold ore don't spawn.

**Comment by LeQwouincy** [comment]
After using this :
      "block": "minecrat:gold_ore",
      "size": 80,
      "count": 90,
      "bottomOffset": 0,
      "topOffset": 0,
      "maxY": 50
I saw that the world generate the "space" for gold ore,
But it's void.
![2019-05-14_16 22 04](https://user-images.githubusercontent.com/49834383/57705642-8e6fa780-7664-11e9-9ab4-33502059663c.png)

**Comment by angelnc1989** [comment]
You missed an f in Minecraft

**Comment by Draylar** [comment]
yeah... not sure what's causing this-- I noticed it with refined machinery ore, trying to figure it out now.

**Comment by LeQwouincy** [comment]
that's actually due to the missing f

**Comment by Draylar** [comment]
Fixed in 1.4.0.
